### ISSUE TITLE
Ethernet Addresses not getting printed properly.

### ISSUE THREAD

**Issue by adwait1-g** [Rithesh17/Network-Monitoring-Tool#1]
Build the executable in this manner.

$ gcc main.c ether_handle.c packcap.c -lpcap

Ignore the warnings. They are mostly harmless.

$ sudo ./a.out

![ethernet addresses not getting printed properly](https://user-images.githubusercontent.com/22262158/37419604-d50c361a-27da-11e8-9523-35f481e157d7.png)

**Comment by adwait1-g** [comment]
@Rithesh17 Please resolve it. I checked. Didnt get the error.

**Comment by Rithesh17** [comment]
I guess size of the src_eth_addr in struct pkp_packet_global isn't sufficient. Give it a larger size (say, 20).

I got something like this.
![screenshot from 2018-03-15 00-10-13](https://user-images.githubusercontent.com/26902904/37424061-8c04fd5c-27e5-11e8-9de3-f97555b40819.png)

**Comment by adwait1-g** [comment]
Peace!
