### ISSUE TITLE
csv file needed

### ISSUE THREAD

**Issue by Rithesh17** [Rithesh17/Network-Monitoring-Tool#2]
For the packet information table to be added, a csv file is needed.

Columns (in this order):
Serial Number
Source IP address
Destination IP address
Source Ethernet Address
Destination Ethernet Address
Protocol
Length of packet
Time of capture

**Comment by adwait1-g** [comment]
Will do it!

**Comment by adwait1-g** [comment]
Packet no.
Frame length.
Source ethernet address
Destination ethernet address
layer-3 protocol
Source IP address(IPv4)
Destination IP addres(IPv4)
Layer 4 protocol
Source port (TCP , UDP)
Destination Port(TCP , UDP)
